---
permalink: upgrade/task_upgrade_snapcenter.html 
sidebar: sidebar 
keywords: upgrade, upgrade snapcenter server, windows 
summary: 您可以使用SnapCenter 「伺服器安裝程式執行檔」來升級SnapCenter 「伺服器」。 
---
= 升級 Windows 主機上的 SnapCenter 伺服器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您應該升級SnapCenter伺服器以存取最新版本中提供的最新功能和增強功能。

.開始之前
* 支援Windows更新的SnapCenter 更新必須是最新版的伺服器主機、而且不會有擱置中的系統重新啟動。
* 確保在開始升級之前沒有其他操作正在運行。
* 確保沒有正在執行的作業後，備份SnapCenter儲存庫（MySQL）資料庫。在升級SnapCenter Server 和 Exchange 插件之前建議這樣做。
+
如需相關資訊，請參閱 link:../admin/concept_manage_the_snapcenter_server_repository.html#back-up-the-snapcenter-repository["備份SnapCenter 這個資訊庫"^]。

* 在SnapCenter伺服器主機或插件主機上備份所有修改後的SnapCenter設定檔。


例如：SnapDriveService.exe.config、SMCoreServiceHost.exe.config等。SnapCenter

* 如果您在SnapCenter 5.0 中安裝了多個版本的自訂插件，則在升級到 6.0 或更高版本之前，您應該執行 powershell cmdlet 從SnapCenter儲存庫（NSM 資料庫）中刪除所有早期版本的自訂插件（最新版本除外）。
+
** 跑步 `Open-SmConnection`並使用 SnapCenterAdmin 角色憑證登入
** 跑步 `Remove-SmPluginPackage -PluginName M<plug-in name> -PluginVersion <version number>`
+
有關更多信息，請參閱 https://kb.netapp.com/data-mgmt/SnapCenter/SC_KBs/SnapCenter_6.0_upgrade_fails_in_nsm_repository_upgrade_SQL_script_8["升級到SnapCenter 6.0 或更高版本失敗"] 。





.關於這項工作
* 在升級期間， SnapCenter執行 SQL 腳本來更新 NSM 資料庫中的 Exchange 數據，將 DAG 和主機短名稱轉換為 FQDN。這僅適用於將SnapCenter Server 與 Exchange 外掛程式一起使用的情況。
* 如果您已手動將伺服器主機置於維護模式，則升級後選擇*主機*>*啟動計劃*以使伺服器主機退出維護模式。
* 針對Microsoft SQL Server的支援功能、適用於Microsoft Exchange Server的支援功能、以及適用於Microsoft Windows的支援功能、建議您將伺服器和外掛程式主機升級至4.7版、以便運行指令碼路徑。SnapCenter SnapCenter SnapCenter
+
針對原則中已啟用的預先編寫和後製指令碼的現有備份與驗證排程、備份作業會在升級後繼續運作。

+
在「*工作詳細資料*」頁面中、有一則警告訊息建議客戶將指令碼複製到指令碼路徑、然後編輯原則、以提供相對於指令碼路徑的路徑。對於複製生命週期工作、會在子工作層級顯示警告訊息。



.步驟
. 從 NetApp 支援網站下載 SnapCenter 伺服器安裝套件。
+
https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab[]

. 建立網路組態的複本、網址為：C:\Program Files\NetApp\SnapCenter網路應用程式。
. 如果升級失敗，請從 Windows 工作排程器匯出SnapCenter插件主機方案以還原它們。
+
`md d:\\SCBackup``schtasks /query /xml /TN taskname >> "D:\SCBackup\taskname.xml"`

. 如果SnapCenter 未設定儲存庫備份、請建立「支援MySQL資料庫傾印」。
+
`md d:\\SCBackup``mysqldump --all-databases --single-transaction --add-drop-database --triggers --routines --events -u root -p > D:\SCBackup\SCRepoBackup.dmp`

+
出現提示時、請輸入密碼。

. 雙擊下載的 .exe 檔案以啟動SnapCenter伺服器升級。
+
開始升級後， SnapCenter會執行預檢查。如果系統不符合最低要求， SnapCenter會顯示錯誤或警告訊息。繼續之前修復所有錯誤。您可以忽略警告並繼續。

+

NOTE: 安裝舊版的還原伺服器時、將繼續使用現有的MySQL Server儲存庫資料庫密碼。SnapCenter SnapCenter

. 選擇*升級*。
+
如果您在任何階段選擇“*取消*”， SnapCenter將停止升級。  SnapCenter伺服器不會回滾到其先前的狀態。

+
*最佳實務：*登出並重新登錄，或開啟新的瀏覽器來存取SnapCenter使用者介面。



.完成後
* 如果外掛程式是使用 Sudo 使用者安裝、您應該複製 _C ： \ProgramData\NetApp\SnapCenter\Package 儲存庫 \SC_UNIT_plugins_checksum ． txt_ 上的 sha224 金鑰、以更新 /etc/sudoers_ 檔案。
* 您應該在伺服器主機上執行新的資源探索。
+
如果SnapCenter顯示伺服器主機狀態為已停止，請等待一段時間並執行新的發現。您也可以將 *HostRefreshInterval* 參數的值（預設值為 3600 秒）變更為任何大於 10 分鐘的值。

* 如果升級失敗，請清理失敗的安裝，重新安裝先前的SnapCenter版本，並將 NSM 資料庫還原到先前的狀態。
* 升級伺服器主機之後，您也必須先升級外掛程式，才能新增任何儲存系統。

