---
permalink: install/task_create_an_ontap_cluster_role_with_minimum_privileges.html 
sidebar: sidebar 
keywords: ONTAP cluster role, privileges 
summary: 您應該建立ONTAP 具有最低權限的支援功能、以便不必使用ONTAP 這個功能來SnapCenter 執行動作。 
---
= 以ONTAP 最低權限建立叢集角色
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您應該建立ONTAP 具有最低權限的支援功能、以便不必使用ONTAP 這個功能來SnapCenter 執行動作。您可以執行數ONTAP 個CLI命令來建立ONTAP 一個不含指令集的叢集角色、並指派最低權限。

*步驟*

. 在儲存系統上、建立角色並將所有權限指派給該角色。
+
`security login role create –vserver <cluster_name\>- role <role_name\> -cmddirname <permission\>`

+

NOTE: 您應該針對每個權限重複此命令。

. 建立使用者並將角色指派給該使用者。
+
`security login create -user <user_name\> -vserver <cluster_name\> -application ontapi -authmethod password -role <role_name\>`

. 解除鎖定使用者。
+
`security login unlock -user <user_name\> -vserver <cluster_name\>`





== 用於建立叢集角色和指派權限的CLI命令ONTAP

您應該執行幾ONTAP 個CLI命令來建立叢集角色並指派權限。


NOTE: 從 SnapCenter 5.0 開始，叢集管理使用者僅支援 REST API 。如果您想要使用非叢集管理來建立角色、則應使用 ZAPI 。

* `security login role create -vserver Cluster_name or cluster_name -role Role_Name -cmddirname "metrocluster show" -access readonly`
* `security login role create -vserver Cluster_name or cluster_name -role Role_Name -cmddirname "cluster identity modify" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "cluster identity show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "cluster modify" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "cluster peer show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "cluster show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "event generate-autosupport-log" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "job history show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "job show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "job stop" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun create" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun delete" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun igroup add" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun igroup create" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun igroup delete" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun igroup modify" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun igroup rename" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun igroup show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun mapping add-reporting-nodes" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun mapping create" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun mapping delete" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun mapping remove-reporting-nodes" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun mapping show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun modify" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun move-in-volume" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun offline" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun online" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun persistent-reservation clear" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun resize" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun serial" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "network interface create" -access readonly`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "network interface delete" -access readonly`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "network interface modify" -access readonly`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "network interface show" -access readonly`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "security login" -access readonly`
* `security login role create -role Role_Name -cmddirname "snapmirror create" -vserver Cluster_name -access all`
* `security login role create -role Role_Name -cmddirname "snapmirror list-destinations" -vserver Cluster_name -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "snapmirror policy add-rule" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "snapmirror policy create" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "snapmirror policy delete" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "snapmirror policy modify" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "snapmirror policy modify-rule" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "snapmirror policy remove-rule" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "snapmirror policy show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "snapmirror restore" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "snapmirror show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "snapmirror show-history" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "snapmirror update" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "snapmirror update-ls-set" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "system license add" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "system license clean-up" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "system license delete" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "system license show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "system license status show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "system node modify" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "system node show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "system status show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "version" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume clone create" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume clone show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume clone split start" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume clone split stop" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume create" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume destroy" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume file clone create" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume file show-disk-usage" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume modify" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume snapshot modify-snaplock-expiry-time" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume offline" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume online" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume qtree create" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume qtree delete" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume qtree modify" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume qtree show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume restrict" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume snapshot create" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume snapshot delete" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume snapshot modify" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume snapshot promote" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume snapshot rename" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume snapshot restore" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume snapshot restore-file" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume snapshot show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume snapshot show-delta" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume unmount" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver cifs create" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver cifs delete" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver cifs modify" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver cifs share modify" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver cifs share create" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver cifs share delete" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver cifs share modify" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver cifs share show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver cifs show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver create" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver export-policy create" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver export-policy delete" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver export-policy rule create" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver export-policy rule delete" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver export-policy rule modify" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver export-policy rule show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver export-policy show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver iscsi connection show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver modify" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver show" -access all`

